import { Entity } from 'megalodon';

import { Persistence } from './persistence';

export function getHomeTimeline(per: Persistence): Promise<Array<Entity.Status>> {
    return Promise.resolve([
        // # REGULAR
        {
            "id": "109319524204782441",
            "uri": "https://masto.pt/users/smsantos/statuses/109319524117908219",
            "url": "https://masto.pt/@smsantos/109319524117908219",
            "account": {
                "id": "109269215760736262",
                "username": "smsantos",
                "acct": "smsantos@masto.pt",
                "display_name": "Sandra",
                "locked": false,
                "bot": false,
                "discoverable": false,
                "group": false,
                "created_at": "2022-11-01T00:00:00.000Z",
                "note": "<p>Pró caralho agora também no masto (bio com aprovação da Isa_ssdd@masto.pt)</p>",
                "url": "https://masto.pt/@smsantos",
                "avatar": "https://files.mastodon.social/cache/accounts/avatars/109/269/215/760/736/262/original/68130cc0023cbd1e.jpeg",
                "avatar_static": "https://files.mastodon.social/cache/accounts/avatars/109/269/215/760/736/262/original/68130cc0023cbd1e.jpeg",
                "header": "https://files.mastodon.social/cache/accounts/headers/109/269/215/760/736/262/original/7f8104f0ce72b379.jpeg",
                "header_static": "https://files.mastodon.social/cache/accounts/headers/109/269/215/760/736/262/original/7f8104f0ce72b379.jpeg",
                "followers_count": 183,
                "following_count": 112,
                "statuses_count": 896,
                "last_status_at": "2022-11-10",
                "emojis": [],
                "fields": []
            },
            "in_reply_to_id": "109319522332109236",
            "in_reply_to_account_id": "109251486243128243",
            "reblog": null,
            "content": "<p><span class=\"h-card\"><a href=\"https://masto.pt/@OnceUponAGoblin\" class=\"u-url mention\" rel=\"nofollow noopener noreferrer\" target=\"_blank\">@<span>OnceUponAGoblin</span></a></span> <span class=\"h-card\"><a href=\"https://mas.to/@cheiraesturro\" class=\"u-url mention\" rel=\"nofollow noopener noreferrer\" target=\"_blank\">@<span>cheiraesturro</span></a></span> estava com saudades nossas</p>",
            "plain_content": null,
            "created_at": "2022-11-10T12:32:38.000Z",
            "emojis": [],
            "replies_count": 0,
            "reblogs_count": 0,
            "favourites_count": 0,
            "reblogged": false,
            "favourited": false,
            "muted": false,
            "sensitive": false,
            "spoiler_text": "",
            "visibility": "public",
            "media_attachments": [],
            "mentions": [
                {
                    "id": "109251486243128243",
                    "username": "OnceUponAGoblin",
                    "url": "https://masto.pt/@OnceUponAGoblin",
                    "acct": "OnceUponAGoblin@masto.pt"
                },
                {
                    "id": "109315774379548034",
                    "username": "cheiraesturro",
                    "url": "https://mas.to/@cheiraesturro",
                    "acct": "cheiraesturro@mas.to"
                }
            ],
            "tags": [],
            "card": null,
            "poll": null,
            "application": null,
            "language": "pt",
            "emoji_reactions": [],
            "bookmarked": false,
            "quote": false
        },
        // CW
        {
            "id": "109319626972813282",
            "uri": "https://mastodon.green/users/Bossito/statuses/109319626921729243/activity",
            "url": null,
            "account": {
                "id": "109246602710412541",
                "username": "Bossito",
                "acct": "Bossito@mastodon.green",
                "display_name": "bossito :blobcatreading:",
                "locked": true,
                "bot": false,
                "discoverable": true,
                "group": false,
                "created_at": "2022-10-28T00:00:00.000Z",
                "note": "<p>ex-blogger e agora ex-twitter </p><p>de bruxelas com ardor</p><p><a href=\"https://mastodon.green/tags/StandUpForUkraine\" class=\"mention hashtag\" rel=\"nofollow noopener noreferrer\" target=\"_blank\">#<span>StandUpForUkraine</span></a> 🇺🇦</p><p><a href=\"https://mastodon.green/tags/Eurovision\" class=\"mention hashtag\" rel=\"nofollow noopener noreferrer\" target=\"_blank\">#<span>Eurovision</span></a> 🎶 <a href=\"https://mastodon.green/tags/GreenPolitics\" class=\"mention hashtag\" rel=\"nofollow noopener noreferrer\" target=\"_blank\">#<span>GreenPolitics</span></a> 🌱 <a href=\"https://mastodon.green/tags/incunabulos\" class=\"mention hashtag\" rel=\"nofollow noopener noreferrer\" target=\"_blank\">#<span>incunabulos</span></a> 📚 <a href=\"https://mastodon.green/tags/Bread\" class=\"mention hashtag\" rel=\"nofollow noopener noreferrer\" target=\"_blank\">#<span>Bread</span></a> 🍞 <a href=\"https://mastodon.green/tags/Brussels\" class=\"mention hashtag\" rel=\"nofollow noopener noreferrer\" target=\"_blank\">#<span>Brussels</span></a> 🇧🇪 <a href=\"https://mastodon.green/tags/EUpolitics\" class=\"mention hashtag\" rel=\"nofollow noopener noreferrer\" target=\"_blank\">#<span>EUpolitics</span></a> 🇪🇺 <a href=\"https://mastodon.green/tags/Gay\" class=\"mention hashtag\" rel=\"nofollow noopener noreferrer\" target=\"_blank\">#<span>Gay</span></a> 🌈 mostly in <a href=\"https://mastodon.green/tags/Portuguese\" class=\"mention hashtag\" rel=\"nofollow noopener noreferrer\" target=\"_blank\">#<span>Portuguese</span></a> 🇵🇹</p>",
                "url": "https://mastodon.green/@Bossito",
                "avatar": "https://files.mastodon.social/cache/accounts/avatars/109/246/602/710/412/541/original/30bec7081d542d33.jpg",
                "avatar_static": "https://files.mastodon.social/cache/accounts/avatars/109/246/602/710/412/541/original/30bec7081d542d33.jpg",
                "header": "https://files.mastodon.social/cache/accounts/headers/109/246/602/710/412/541/original/cf90ad2faf1a6319.jpg",
                "header_static": "https://files.mastodon.social/cache/accounts/headers/109/246/602/710/412/541/original/cf90ad2faf1a6319.jpg",
                "followers_count": 1324,
                "following_count": 1357,
                "statuses_count": 2122,
                "last_status_at": "2022-11-10",
                "emojis": [
                    {
                        "shortcode": "blobcatreading",
                        "url": "https://files.mastodon.social/cache/custom_emojis/images/000/440/732/original/4cf153521c62b542.png",
                        "static_url": "https://files.mastodon.social/cache/custom_emojis/images/000/440/732/static/4cf153521c62b542.png",
                        "visible_in_picker": true
                    }
                ],
                "fields": []
            },
            "in_reply_to_id": null,
            "in_reply_to_account_id": null,
            "reblog": {
                "id": "109318428532790230",
                "uri": "https://social.zapletalovi.com/users/lukas/statuses/01GHG8G4H9RFRXJ394QQHWYWK3",
                "url": "https://social.zapletalovi.com/@lukas/statuses/01GHG8G4H9RFRXJ394QQHWYWK3",
                "account": {
                    "id": "109297885018650908",
                    "username": "lukas",
                    "acct": "lukas@zapletalovi.com",
                    "display_name": "Lukáš Zapletal",
                    "locked": false,
                    "bot": false,
                    "discoverable": false,
                    "group": false,
                    "created_at": "2022-11-06T00:00:00.000Z",
                    "note": "<p>Software Engineer at Red Hat, tech guy, Linux, Open Source, EDM/DJ, bedroom producer. My stream is pure tech and jokes, no politics, no real life. My nick is lzap. That's el-zet-ej-pi.</p>",
                    "url": "https://social.zapletalovi.com/@lukas",
                    "avatar": "https://files.mastodon.social/cache/accounts/avatars/109/297/885/018/650/908/original/8cd2639969951f59.jpeg",
                    "avatar_static": "https://files.mastodon.social/cache/accounts/avatars/109/297/885/018/650/908/original/8cd2639969951f59.jpeg",
                    "header": "https://files.mastodon.social/cache/accounts/headers/109/297/885/018/650/908/original/e4b8722ad2bcd280.jpeg",
                    "header_static": "https://files.mastodon.social/cache/accounts/headers/109/297/885/018/650/908/original/e4b8722ad2bcd280.jpeg",
                    "followers_count": 9,
                    "following_count": 18,
                    "statuses_count": 40,
                    "last_status_at": "2022-11-10",
                    "emojis": [],
                    "fields": []
                },
                "in_reply_to_id": null,
                "in_reply_to_account_id": null,
                "reblog": null,
                "content": "<p>Mastodon, the free, open-source social network server based on ActivityPub is written in Ruby on Rails and the network is experiencing influx of new users. Mastodon administrators are finding how difficult and costly is to scale Ruby on Rails applications the hard way. I’ve spent a deacde working on a large Ruby on Rails project, much larger than Mastodon. Let me quickly describe what is going on. Disclaimer: This post is solely based on my experience with scaling other Ruby on Rails applications, take this with a grain of salt. Also, I’d appreciate comments at @lukas@zapletalovi.com.<br><br>People often think that Ruby on Rails is slow because Ruby is slow, according to various benchmarks and shootouts. Well, while Ruby is not fast at all, it is not the primary reason why that is. See, most web applications, including Mastodon, do not perform CPU-intensive tasks. Most of the time, CPU is actually waiting for data to be read or written from network (client, database, redis) or disk (cache). Even if you upgrade to the most recent Ruby 3.2, which is the fastest of all Ruby versions, it won’t help at all.<br><br>Backend software these days need to respond to many of HTTP requests, when a service is under load we are speaking about hundreds or even thousands of requests per second. A single process (instance of software running on an operating system) with naive implementation can handle as much as one request. To be able to handle more, requests must be dealt concurrently, which is a very complex topic but let’s keep in simple. The solution is to create multiple execution threads that can run concurrently on the program level and ideally in parallel on the operating system level to utilize as much CPU resources available.<br><br>It is too long, read on at:<br><br><a href=\"https://lukas.zapletalovi.com/2022/11/why-mastodon-instances-are-difficult-to-scale.html\" rel=\"nofollow noopener noreferrer\" target=\"_blank\">lukas.zapletalovi.com/2022/11/why-mastodon-instances-are-difficult-to-scale.html</a><br><br>Feel free to put my own instance through a scale test by boosting this post. Let's see how good really I am in maintaining server software... :-)</p>",
                "plain_content": null,
                "created_at": "2022-11-10T07:54:01.000Z",
                "emojis": [],
                "replies_count": 5,
                "reblogs_count": 21,
                "favourites_count": 2,
                "reblogged": false,
                "favourited": false,
                "muted": false,
                "sensitive": true,
                "spoiler_text": "Why Mastodon instances are difficult to scale (long)",
                "visibility": "public",
                "media_attachments": [],
                "mentions": [],
                "tags": [],
                "card": {
                    "url": "https://lukas.zapletalovi.com/2022/11/why-mastodon-instances-are-difficult-to-scale.html",
                    "title": "Why Mastodon instances are difficult to scale - Lukáš Zapletal",
                    "description": "Lukáš Zapletal lzap Blog",
                    "type": "link",
                    "author_name": "",
                    "author_url": "",
                    "provider_name": "",
                    "provider_url": "",
                    "html": "",
                    "width": 0,
                    "height": 0,
                    "image": null,
                    "embed_url": "",
                    "blurhash": null
                },
                "poll": null,
                "application": null,
                "language": null,
                "emoji_reactions": [],
                "bookmarked": false,
                "quote": false
            },
            "content": "",
            "plain_content": null,
            "created_at": "2022-11-10T12:58:47.000Z",
            "emojis": [],
            "replies_count": 0,
            "reblogs_count": 0,
            "favourites_count": 0,
            "reblogged": false,
            "favourited": false,
            "muted": false,
            "sensitive": false,
            "spoiler_text": "",
            "visibility": "public",
            "media_attachments": [],
            "mentions": [],
            "tags": [],
            "card": null,
            "poll": null,
            "application": null,
            "language": null,
            "emoji_reactions": [],
            "bookmarked": false,
            "quote": false
        },
        // POLL
        {
            "id": "109315556310564600",
            "uri": "https://masto.pt/users/tarantelma/statuses/109315524710965554",
            "url": "https://masto.pt/@tarantelma/109315524710965554",
            "account": {
                "id": "109274668188666170",
                "username": "tarantelma",
                "acct": "tarantelma@masto.pt",
                "display_name": "Telma Tavares",
                "locked": false,
                "bot": false,
                "discoverable": true,
                "group": false,
                "created_at": "2022-11-02T00:00:00.000Z",
                "note": "<p>Designer 24/7.<br>\"Génia das t-shirts\" <a href=\"https://masto.pt/tags/pordosol\" class=\"mention hashtag\" rel=\"nofollow noopener noreferrer\" target=\"_blank\">#<span>pordosol</span></a><br>Avatar do Ben Wiseman, banner do Six Feet Under. <br>She/Her.</p>",
                "url": "https://masto.pt/@tarantelma",
                "avatar": "https://files.mastodon.social/cache/accounts/avatars/109/274/668/188/666/170/original/8948b8580b8ba695.gif",
                "avatar_static": "https://files.mastodon.social/cache/accounts/avatars/109/274/668/188/666/170/static/8948b8580b8ba695.png",
                "header": "https://files.mastodon.social/cache/accounts/headers/109/274/668/188/666/170/original/ac1f43f6a4526a77.jpeg",
                "header_static": "https://files.mastodon.social/cache/accounts/headers/109/274/668/188/666/170/original/ac1f43f6a4526a77.jpeg",
                "followers_count": 417,
                "following_count": 387,
                "statuses_count": 222,
                "last_status_at": "2022-11-09",
                "emojis": [],
                "fields": [
                    {
                        "name": "Site",
                        "value": "eatyourcake.pt",
                        "verified_at": null
                    },
                    {
                        "name": "Loja",
                        "value": "foreversandevers.pt",
                        "verified_at": null
                    }
                ]
            },
            "in_reply_to_id": null,
            "in_reply_to_account_id": null,
            "reblog": null,
            "content": "<p>Qual o hashtag para o gang dos filmes? Tivemos várias sugestões, votem na que preferem:</p>",
            "plain_content": null,
            "created_at": "2022-11-09T19:35:32.000Z",
            "emojis": [],
            "replies_count": 1,
            "reblogs_count": 3,
            "favourites_count": 0,
            "reblogged": false,
            "favourited": false,
            "muted": false,
            "sensitive": false,
            "spoiler_text": "",
            "visibility": "public",
            "media_attachments": [],
            "mentions": [],
            "tags": [],
            "card": null,
            "poll": {
                "id": "287977",
                "expires_at": "2022-11-10T19:35:32.000Z",
                "expired": false,
                "multiple": false,
                "votes_count": 34,
                "voters_count": 34,
                "voted": false,
                "own_votes": [],
                "options": [
                    {
                        "title": "#ParaisoFilmes",
                        "votes_count": 14
                    },
                    {
                        "title": "#mastolumiere",
                        "votes_count": 10
                    },
                    {
                        "title": "#TheMastoPictureShow",
                        "votes_count": 6
                    },
                    {
                        "title": "#lumiere",
                        "votes_count": 4
                    }
                ],
                "emojis": []
            },
            "application": null,
            "language": "pt",
            "emoji_reactions": [],
            "bookmarked": false,
            "quote": false
        }
    ] as any as Array<Entity.Status>);
}
